# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_todoitem_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='name',
            field=models.CharField(default='name', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.TodoList'),
        ),
    ]
